include/taskomat/Step.h, src/Step.cc, tests/test_serialize_sequence.cc
**[why]**
The serialisation process is designed to accept any number of whitespaces after the colon. This will suppress any whitespaces that were part of the label to be restored correctly.
**[how]**
Just forbid labels that can not be restored. Although we could instead install several other attempts to allow leading or trailing whitespaces in the label the question is: Is the freedom to allow such labels worth the more complicated code?
For this commit the answer is: no, and so whitespaced labels are forbidden.
Fixes:
https://mcs-gitlab.desy.de/doocs/doocs-high-level-support/libtaskomat/-/issues/19
=> Step: Prevent labels that we can not serialize

include/taskomat/Message.h, include/taskomat/Step.h, src/Step.cc, tests/test_Message.cc, tests/test_Step.cc
...to `Step` and `Message`.
Example from the tests:
```c++
TEST_CASE("Message: Dump to stream", "[Message]")
{
Message msg;
msg.set_type(Message::Type::step_started)
.set_timestamp(TimePoint{})
.set_text("Beware of the foxes")
.set_index(32);
std::stringstream ss{ };
[...]
```
----
This ALSO fixes an error in the tests, too lazy to create a separate PR.
The tests should have tested if the `modification_timestamp` has been changed on `set_*()` access, but did not actually check it.
=> Add fluid interface

include/taskomat/Sequence.h, src/Sequence.cc, tests/test_Executor.cc, tests/test_Sequence.cc
[why]
A sequence must have a name to be recognised by the users. The previous anonymous sequence is therefore forbidden.
[how]
In the previous constructor you can create a `Sequence` without any name. The sequence then indirectly uses `anonymous` as its name. In practice this can be cumbersome by the users who cannot distinguish between sequence names. Therefore the user is forced to give a sequence a reliable and expressive name.
Fixes: #7 
_Edit: Add link to issue_
=> Ban a sequence without a name

include/taskomat/Sequence.h, tests/test_Executor.cc
**[why]**
As shown in #19, `Executor::is_busy()` may return false almost directly after a call to `Executor::run_asynchronously()`, depending on the load of the system.
**[how]**
Do not test for conditions that are not logically guaranteed.
Fixes: #19
=> Fix failing Executor test by not testing un-guaranteed conditions

include/taskomat/Message.h, include/taskomat/lua/luaconf.h, src/Step.cc, tests/test_Executor.cc, tests/test_Step.cc
This MR changes the definition of the LUAI_TRY macro to allow the correct reporting of C++ exceptions from user code inside Lua. It also includes a unit test by Fini for checking that.
**[why]**
We have a fundamental problem with exceptions in Lua and Sol. Our C++-compiled Lua throws "lua_longjmp*" as C++ exceptions for its internal error handling (as opposed to a C-compiled Lua that would use longjmp, with even worse side effects). Unfortunately, it catches its own exceptions with a "catch(...)".
Sol2 knows two modes of operation: With SOL_EXCEPTIONS_SAFE_PROPAGATION == 1, it assumes that user exceptions can safely bubble through the Lua engine and does not catch or handle them. In this case, Lua's "catch(...)" statement, however, will accidentally catch these user exceptions and report …
=> Bugfix: Change lua exception handling

include/taskolib/Step.h, include/taskolib/lua/luaconf.h, include/taskolib/sol/sol/config.hpp, meson.build, src/Step.cc, src/lua_details.cc, src/lua_details.h, tests/test_Step.cc, tests/test_lua_details.cc
This is yet another take on exception handling, this time with the new Sol2 version 3.3.0 that Fini introduced. It finally allows us to treat C++ exceptions like Lua exceptions and intercept them with `pcall()`.
With Sol 3.3.0, there are new configuration macros that allow enabling C/C++ function call trampolines without breaking Lua's internal exception propagation mechanism. Hence, we no longer need to modify Lua's LUAI_CATCH macro, but can use the default one.
For enabling the trampoline, we use SOL_PROPAGATE_EXCEPTIONS == 0 instead of the old SOL_SAFE_EXCEPTION_PROPAGATION == 1.
There are a number of related changes and extended tests as well.
=> Better exception handling with Sol 3.3.0

src/lua_details.h
**[why]**
It works now on our platform, but variable access could break.
**[how]**
The concrete types of the variables in the state are not actually defined to be some C++ type but have their own alias. Use that.
----
I fear plain `long long` and `double` has been used in a lot more places in the codebase, where it should have been `LUA_INTEGER` and `LUA_NUMBER`.
Came up when creating #28, because that uses these functions.
=> Step: Use correct type to access variables in state

meson.build, tests/meson.build, tests/test_self_containment.cc.in
Do a header self-containment test.
And find headers that have bugs, but that we do not include in the normal build/test processes.
See https://github.com/taskolib/taskolib/pull/27#discussion_r1010232305
=> Test all headers

src/Step.cc, tests/test_Step.cc
**[why]**
If a Step has an error (syntax or runtime), or aborts changed variables from the context are not synced back to the context.
This makes it impossible to use the variables that are handed over from Step to Step in a Sequence to keep information stored into them if the Step that stored the information errors out.
**[how]**
Copy the context variables after the script returned from state to context always. Regardless if the script errored out or not.
Fixes: #24 
-----
Also dropped some empty lines; that code there is _very_ verbose and the length of the function names border on Koerperverletzung ;-D
=> Step: Resync variables from state to context also on errors

include/taskolib/sol/sol/sol.hpp, src/Step.cc
**[why]**
Compiling with clang issues this warning (clang 10.0 and 15.0 tested):
```
../include/taskolib/sol/sol/sol.hpp:14541:32: warning: unknown warning group '-Wmaybe-uninitialized', ignored [-Wunknown-warning-option]
#pragma GCC diagnostic ignored "-Wmaybe-uninitialized"
^
../include/taskolib/sol/sol/sol.hpp:17294:32: warning: unknown warning group '-Wmaybe-uninitialized', ignored [-Wunknown-warning-option]
#pragma GCC diagnostic ignored "-Wmaybe-uninitialized"
```
**[how]**
Check if the compiler does know the warning, before trying to turn the warning off.
**[note]**
Also remove warning:
../src/Step.cc:40:23: warning: unused variable 'always_false_v' [-Wunused-const-variable]
inline constexpr bool always_false_v = false;
^
(The function is only used when we want to throw an …
=> Sol: Fix clang compiler warning

src/Sequence.cc, src/Step.cc, src/internals.cc, src/internals.h, src/lua_details.cc, tests/meson.build, tests/test_Sequence.cc, tests/test_internals.cc
By default, `Step` errors are reported via the *error* channel and probably displayed to the user (the DOOCS Taskomat does that by default). As such error messages should never contain our internal abort marker, this PR goes to some length to filter them out.
We implement a new function `remove_abort_markers_from_error_message()` and add unit tests for it. This function is used both in `Sequence::execute()` and in `Step::execute()` to find and remove abort markers. It also interprets the meaning of the abort markers and returns one of the enum class values `uncaught_error`, `terminated_by_script`, or `aborted`.
=> Refactor abort handling and suppress abort markers in Step error messages

include/taskolib/Executor.h, src/Executor.cc, tests/test_Executor.cc
This PR adds a test that demonstrates issue #40 (`Executor` context being overwritten indiscriminately when running a parallel sequence) and implements a fix.
**[why]**
A sequence executed in parallel by an `Executor` should sync back its context variables to the calling thread, but it accidentally synced back the entire context. This effectively overwrote other fields, most notably the output functions.
**[how]**
Return only the variables in `Executor`'s future, not the entire `Context` object.
Fixes #40.
=> Bugfix: Do not overwrite executor context

.github/workflows/build_and_run_tests.yml
**[why]**
We recently had a PR that had failing tests in the CI, but you can not look into the details.
**[how]**
Add a build artifact with the Meson logs if the build fails.
=> CI: Make error logs availabe if CI fails

include/taskolib/sol/sol/config.hpp, src/lua_details.cc, src/lua_details.h, tests/meson.build, tests/test_Step.cc, tests/test_lua_details.cc
**[why]**
Error messages from Sol2 are usually littered with unhelpful references to the chunk name (`[string "..."]:`) both at the beginning of the message and within the stack trace. This chunk name is useful for normal file-based Lua execution, but not in our case where only one string is executed.
Also, throwing a C++ exception not derived from `std::exception` from within Lua causes the confusing error message:
```
lua: error: stack index 1, expected string, received function
``` 
See the comment in the code for an explanation.
**[how]**
Set the chunk name to an unlikely Unicode character (an anchor symbol) and remove the chunk name references via `replace()`. Also, if the error message is the one above, return "Unknown C++ exception" instead.
=> Process error messages in execute_lua_script_safely()

tests/test_Executor.cc
**[why]**
The "run sequence asynchronously with throw" test for the Executor class tested for `Executor::is_busy()` directly after an `Executor::run_asynchronously()` call. While this is very likely to return true, it is not guaranteed and actually fails on some Github test systems.
**[how]**
Test only for conditions that are independent of timing.
=> Test only strictly guaranteed conditions

include/taskolib/Context.h, src/Step.cc, tests/test_Context.cc, tests/test_Sequence.cc, tests/test_Step.cc
**[why]**
These two basic Lua types can not be forwarded from one step to the next.
**[how]**
Add the `bool` type just like the others.
`nil` in Lua means 'does not exist', so `x = nil` means that the variable
`x` becomes non-existing afterwards. That means that we need to remove the
variable also from the context in that case. We do not need a 'nil
type'; `nil` is just the absence of anything there.
The Lua types `userdata`, `function`, and `table` can still not be
forwarded from one Step to the next.
Fixes: #32
=> Step: Add bool and nil context variable types

examples/execute_step.cc, include/taskolib/Context.h, src/Step.cc, src/lua_details.cc, src/lua_details.h, tests/test_Context.cc, tests/test_Executor.cc, tests/test_Sequence.cc, tests/test_Step.cc, tests/test_lua_details.cc
**[why]**
When we want to interface with the Lua data types that are held in the Lua state we need to use specific C++ types. These types (for example `long long` have been used directly and often it is not so clear why some type is used.
**[how]**
Use alias types that clearly communicate to the reader of the case that some value for interfacing with Lua is to be used/created/stored.
When using these also consistently to create assignments the whole problem of variant's char*-to-bool quirk goes away. We could even introduce not alias types but real types instead to be even more type save.
**[note]**
Also unify the test code a bit.
Also change how the values in the Context.variables are compared (sometimes). We compare the values, not the variants.
Also add missing LuaBool export from …
=> Introduce aliases for Lua types

include/taskolib/Executor.h, src/Executor.cc, src/Sequence.cc, tests/test_Executor.cc, tests/test_LockedQueue.cc
**[why]**
When a Sequence runs asynchronously and produces so much messages that the message queue gets clogged up we can not force-stop the Sequence or destruct the Executor anymore.
**A)**
The reason is that we can not call `cancel()` on the Executor. The executing thread is already waiting for a slot in the queue. But when we call `cancel()` the Executor just waits for the thread to become ready (joinable). That will never happen, because it waits on the queue, ...
**B)**
When we want to cancel the Sequence this is detected too late (or never) under certain circumstances, because it is only checked in the running Lua VM debug hook.
**[how]**
**A)**
Distinguish between 'last resort' `cancel()` and 'orderly' `cancel()`. Introduce a new function for the later, that takes a Sequence …
=> Executor: Fix forceful cancellation

include/taskolib/Sequence.h, src/Sequence.cc, tests/test_Sequence.cc
We generally forbid the modification of functional parts of the sequence during its execution. The same should be true for `set_step_setup_script()`.
=> Throw if set_step_setup_script() called on running Sequence

src/Sequence.cc
[why]
When you have a sequence of lots of action Steps the termination flag will not be checked in between the Steps.
[how]
Check the flag each time before a Step is called.
Reported-by: Lars Froehlich <lars.froehlich@desy.de>
Signed-off-by: Fini Jastrow <ulf.fini.jastrow@desy.de>
=> Sequence: Fix user-termination on many action Steps

README.md, data/doxygen.h, examples/execute_step.cc, include/taskolib/Context.h, include/taskolib/Sequence.h, include/taskolib/Step.h, include/taskolib/sol/sol/config.hpp, src/deserialize_sequence.cc, src/lua/meson.build, src/lua_details.cc, src/lua_details.h, tests/test_Executor.cc, tests/test_Sequence.cc, tests/test_Step.cc
*[why]*
To cite from https://www.lua.org/about.html:
> "Lua" (pronounced LOO-ah) means "Moon" in Portuguese. As such, it is neither an acronym nor an abbreviation, but a noun. More specifically, "Lua" is a name, the name of the Earth's moon and the name of the language. Like most names, it should be written in lower case with an initial capital, that is, "Lua". Please do not write it as "LUA", which is both ugly and confusing, because then it becomes an acronym with different meanings for different people. So, please, write "Lua" right!
=> Replace "LUA" by "Lua"

.vscode/launch.json, include/taskolib/Sequence.h, src/Sequence.cc, tests/test_Sequence.cc
This PR implements single-step execution in the `Sequence` class.
*[why]*
Executing single steps in isolation is extremely important for debugging.
*[how]*
Add a member function
```cpp
execute_single_step(Context&, CommChannel*, StepIndex) 
```
similar to the existing
```cpp
execute(Context&, CommChannel*)
```
The functions share their main implementation through a private member function `handle_execution()`, which takes care of exception handling and messaging. In a nutshell, `execute()` runs a body of
```cpp
check_syntax();
execute_range(...);
```
whereas `execute_single_step()` runs a body of
```
if (executes_script(step->get_type()))
step->execute(context, comm, step_index);
```
Drive-by commits include renaming a member function, silencing a compiler warning, and some corrections …
=> Execute single step in isolation

include/taskolib/Sequence.h, src/Executor.cc, src/Sequence.cc, tests/test_Sequence.cc
As proposed by Fini in #63, this commit replaces the two Sequence member functions
```cpp
void execute(Context& context, CommChannel* comm_channel);
void execute_single_step(Context& context, CommChannel* comm_channel, StepIndex step_index);
```
by a single one:
```
void execute(Context& context, CommChannel* comm_channel, OptionalStepIndex opt_step_index = gul14::nullopt);
```
The new `execute()` function runs the entire sequence if `opt_step_index == nullopt`, and runs just a single step in isolation if `opt_step_index` contains a valid step index.
IMO the new interface does not convey the user's intent just as well as the old one, so I would tend to keep the old API. It still has its merits to have one less member function. Please let me know what you think.
=> Sequence: Remove execute_single_step() in favor of execute()

include/taskolib/deserialize_sequence.h, include/taskolib/serialize_sequence.h, src/SequenceManager.cc, src/deserialize_sequence.cc, src/serialize_sequence.cc, tests/test_SequenceManager.cc, tests/test_serialize_sequence.cc
[why]
Since there is a possibility to deserialize a step or sequence with the overload operator `operator>>` on a half filled object there is a need to reduce the deserialization functionality. To have a symmetrical view on serializing both operators `operator<<` on sequence and step are as well removed.
[how]
- removing input stream operator `operator>>` for sequence and step in [`deserialize_sequence.h`](https://github.com/taskolib/taskolib/compare/feature/downsize_serdes_functionality?expand=1#diff-c566f86b2558eccdb3e028bfa40bebb0bee25c88804fdc68ef94f597d5f88959)
- removing output stream operator `operator<<` for sequence and step in [`serialize_sequence.h`](https://github.com/taskolib/taskolib/compare/feature/downsize_serdes_functionality?expand=1#diff-6519b439c5fe3d34e95cd8f8bf23c53bf …
=> SerDes: downsizing operators to serialize/deserialize sequence and steps

include/taskolib/Sequence.h, include/taskolib/exceptions.h, src/Executor.cc, src/Sequence.cc, tests/test_Executor.cc, tests/test_Sequence.cc, tests/test_exceptions.cc
This PR makes `Sequence::execute()` return an `optional<Error>` instead of throwing. For improved testing, it also adds comparison operators to the `Error` class.
*[why]*
In virtually all cases in our codebase, exceptions thrown from `Sequence::execute()` were caught immediately with a try...catch block. In this case it makes, arguably, no sense to throw an exception, and returning an optional error directly results in more readable code.
As a side effect, the value returned from `Sequence::execute()` is now identical to what gets returned from `Sequence::get_error()` afterwards. This symmetry was simply not visible before.
=> Make Sequence::execute return optional<Error> instead of throwing

include/meson.build, include/taskolib/CommChannel.h, include/taskolib/Context.h, include/taskolib/Executor.h, include/taskolib/Message.h, include/taskolib/default_message_callback.h, src/Executor.cc, src/Sequence.cc, src/Step.cc, src/default_message_callback.cc, src/lua_details.cc, src/lua_details.h, src/meson.build, src/send_message.cc, src/send_message.h, tests/meson.build, tests/test_Executor.cc, tests/test_Message.cc, tests/test_Sequence.cc, tests/test_Step.cc, tests/test_send_message.cc
This pull request changes the callbacks provided by the `Context` class: Where there used to be multiple callbacks for producing various types of output, there is now just one hook (the `message_callback_function`) that gets called whenever a message is being processed. Consequently, this hook only receives a reference to the processed message as a parameter.
`send_message()` is now the main hub for calling user hooks. Its signature changes because it needs access to the `Context` for that, with a lot of consequential downstream changes.
These modifications also have an impact on how `print()` is implemented: It basically just does the usual work of stringifying and concatenating its arguments, but then just proceeds to send a message of type `Type::output`. It is up to the user to …
=> Add messaging hooks and rework callback architecture

src/lua_details.cc, tests/test_Step.cc
[why]
We do not include the os library because it contains a lot of "dangerous" functions.
Bit it also contains some very useful and harmess functions like date().
[how]
Allow a very limited subset of library os in the Lua scripts.
Fixes: #76
=> Include some basic functions from Lua os library

.github/workflows/build_and_run_tests.yml
With the next MR, we'll need libgit2 as a build dependency. This MR installs it in the CI setup.
=> Github CI: Install libgit2

src/internals.cc, src/internals.h
In the Taskomat server log, error messages with newlines are displayed on a single line. This means that there is practically no visual distinction between the error message and the stack trace:
```
5: Created TARGET_ENERGY_MEV property; please configure it. stack traceback: [C]: in function 'base.error' 5: in main chunk
```
This PR tries to make the output a bit more readable: If the message contains a Lua stack trace, the `remove_abort_markers()` function highlights its start by including a UTF-8 bullet symbol to visually separate the main message text from the stack trace.
```
5: Created TARGET_ENERGY_MEV property; please configure it. ● Stack traceback: [C]: in function 'base.error' 5: in main chunk
```
=> Beautify Lua error messages containing stack traces

src/SequenceManager.cc, tests/test_SequenceManager.cc
If a .git directory was present in the sequences folder, it was listed as an empty sequence. This PR makes `SequenceManager` explicitly ignore ".git" folders and adds a test to confirm that.
=> SequenceManager: Ignore .git directory

src/Step.cc, tests/test_Step.cc
This commit makes `Step::execute()` raise an error if an attempt is made to export a variable of unsupported type from the Lua script into the context. This is helpful because users typically expect things like Lua arrays to be exportable and are surprised if they are simply ignored.
=> Make execute() throw when trying to export an unsupported type

include/taskolib/SequenceManager.h, src/SequenceManager.cc, tests/test_SequenceManager.cc
This pull request adds two member functions, `SequenceManager::copy_sequence()` and `SequenceManager::remove_sequence()`, that... well, do what the names say. This is necessary because library users should not (need to) know how their sequences are stored on disk. It is also a preparatory step for introducing Git functionality.
=> Add copy and remove functionality to the SequenceManager

src/SequenceManager.cc, tests/test_SequenceManager.cc
The lib could not remove a sequence folder that had files in it because we used remove() instead of remove_all().
Add a unit test and use remove_all() instead of remove(). :)
=> Fix removal of non-empty sequence folders

include/taskolib/SequenceName.h, src/SequenceName.cc, tests/test_SequenceName.cc
Sequence names are designed to be machine-friendly, and as such are often used as folder or file names. On unixoid operating systems, file names starting with a period designate hidden files. We might want to avoid that by requiring that the first character of a sequence name must not be a period (".").
Closes #98.
=> Disallow sequence names starting with a period

include/taskolib/Sequence.h, src/Sequence.cc, tests/test_Sequence.cc
When a sequence fails, the Error object that can be obtained via `Sequence::get_error()` contains the index of the step that caused the error. This also shows up as a red indicator in the Taskomat GUI.
If a step is deleted or inserted before the error step or if the error step itself is deleted, the index is not updated. This means that the wrong step is now indicated in red.
This PR corrects this behavior via modifications to `Sequence::pop_back()`, `Sequence::insert()`, and `Sequence::erase()`.
Closes #102.
=> Bugfix: Correct error info when erasing or inserting steps

include/taskolib/SequenceManager.h, src/SequenceManager.cc
[why]
When an unmodified Sequence is to be stored an error is thrown. It is hard (but not impossible) to distinguish a real failure from an attempt to "store" no change.
[how]
Do not throw on unmodified Sequences but instead return a boolean that indicates if changes did exist.
Git errors are still exceptions.
This makes the error handling much more easy.
=> SequenceManager: Fix storing unmodified sequences

include/taskolib/SequenceManager.h, src/SequenceManager.cc, tests/test_SequenceManager.cc
This PR removes the automatic renaming of legacy sequence folders (which should never have been in the code according to @Finii :) ). All installations (that we know of) have already moved to the new folder format, so this should not have any impact.
=> Remove automatic renaming of legacy sequence folders

include/taskolib/execute_lua_script.h, src/execute_lua_script.cc, tests/meson.build, tests/test_execute_lua_script.cc
This PR adds a simple free function `load_lua_script()` to check the syntax of a piece of Lua script. This would make it possible to emit a warning if someone presses "Save" on the Taskomat panel and has a syntax error in their code.
There are many possible improvements amd variations here:
- The file name is no longer good. `execute_lua_script.cc` now contains a function called `check_lua_script()` as well. Should we rename?
- The function could create a temporary `sol::state` just to load the script. This would guarantee total isolation at the cost of some more expensive initialization. I do not think there is a bad side effect of calling load repeatedly on some Lua state, but I am also not sure.
As a drive-by fix, this PR also makes sure that the unit tests from …
=> Add load_lua_script(), build forgotten tests

include/taskolib/execute_lua_script.h, src/Step.cc, src/execute_lua_script.cc, tests/test_execute_lua_script.cc
Due to the lack of an `expected` type in C++17, the function was implemented as returning a variant. Unfortunately, dealing with variants is somewhat clumsy and does not convey the intent of having an expected outcome and an error outcome.
Since we have introduced `gul14::expected` in the meantime, we can just use it as the return type. The unit tests show how this simplifies the calling code.
=> Make execute_lua_script() return expected instead of variant

include/taskolib/SequenceManager.h, src/SequenceManager.cc, src/deserialize_sequence.cc, src/deserialize_sequence.h, tests/test_SequenceManager.cc, tests/test_deserialize_sequence.cc
This PR adds a `SequenceManager::import_sequence()` member function that can import a sequence from an arbitrary file system path. Some of the underlying infrastructure is cleaned up and adapted in the process.
=> Import sequence from file system path

include/meson.build, include/taskolib/Sequence.h, include/taskolib/Tag.h, src/Sequence.cc, src/SequenceManager.cc, src/Tag.cc, src/deserialize_sequence.cc, src/deserialize_sequence.h, src/meson.build, tests/meson.build, tests/test_Sequence.cc, tests/test_Tag.cc, tests/test_deserialize_sequence.cc
This is the first step in the direction of a fully-fledged tagging system for Taskolib. We introduce a `Tag` class for tags like `production`, `test`, or `area-51`, and the `Sequence` class gets extended with `get_tags()` and `set_tags()` member functions. SerDes to the `sequence.lua` file is also included.
In the next step, we could extend the `SequenceManager` with functions to list the tags from all sequences.
=> Add tags to categorize sequences

src/deserialize_sequence.cc, src/deserialize_sequence.h, tests/test_deserialize_sequence.cc
This PR extracts `parse_timeout()` from an anonymous namespace, adds documentation and unit tests, and fixes some unexpected behaviors like parsing "10 s" into a timeout of 10 milliseconds.
=> Make parse_timeout() testable and more robust

include/taskolib/Tag.h, tests/test_Tag.cc
This PR adds an `operator+(const std::string&, const Tag&)` and an `operator(const Tag&, const std::string&)`. This is a prerequisite for using `gul14::join()` with a container full of `Tag`s, but it is also useful in general.
=> Tag: Add operator+ to concatenate strings and Tags

include/taskolib/Tag.h, tests/test_Tag.cc
We still cannot use `gul14::join()` on a container full of `Tag`s because we forgot to add a `size()` member function. This PR adds it alongside a few corresponding tests.
=> Tag: Add size() member function
